# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            SoundNodes
tagline:          '连接您钟爱的喇叭'
description:      '追赶流媒体音乐的普及趋势，通过互联的方式提升我们音响的使用体验。'
url:              http://www.soundnodes.com
baseurl:          /

author:
  name:           'SoundNodes'
  url:            http://www.soundnodes.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/soundnodes/soundnodes
